
export enum TorchMode {
  NORMAL = 'NORMAL',
  STROBE = 'STROBE',
  SOS = 'SOS',
  SOUND_REACTIVE = 'SOUND_REACTIVE'
}

/**
 * Interface for lighting configuration generated by AI based on mood/prompt.
 */
export interface MoodConfig {
  color: string;
  pulseSpeed: number;
  intensity: number;
  description: string;
}
